In [1]:
import sys
import scanpy as sc
import anndata as ad
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print("Python version:")
print(sys.version)

print("\nScanpy version:")
print(sc.__version__)

print("\nPandas version:")
print(pd.__version__)

Python version:
3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]

Scanpy version:
1.12.4

Pandas version:
3.0.6

C:\Users\strangers\AppData\Local\Temp\ipykernel_20808\833510663.py:5: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  print(sc.__version__)

In [3]:
from pathlib import Path
import gzip

metadata_file = Path("../data/metadata/GSE221156_series_matrix.txt.gz")

print("File exists:", metadata_file.exists())
print("File path:", metadata_file)

File exists: True
File path: ..\data\metadata\GSE221156_series_matrix.txt.gz

In [4]:
with gzip.open(metadata_file, "rt") as f:
    lines = f.readlines()

print("Number of lines:", len(lines))

for line in lines[:20]:
    print(line.strip())

Number of lines: 97
!Series_title	"Dissecting cell-type specific pathophysiological changes in human type-2 diabetic pancreatic islets using single-cell transcriptomic data"
!Series_geo_accession	"GSE221156"
!Series_status	"Public on Mar 30 2023"
!Series_submission_date	"Dec 16 2022"
!Series_last_update_date	"Aug 21 2026"
!Series_pubmed_id	"41986506"
!Series_summary	"Pancreatic islet (dys)function is central to glucose homeostasis and type 2 diabetes (patho)physiology. Human islets consist of multiple endocrine (alpha, beta, delta, gamma), endothelial, and resident/inflitrating immune cells whose coordinated functions modulate glucose mobilization or disposal. Single cell transcriptome profiling (scRNA-seq) studies have been applied to dissect human islet cellular heterogeneity, identify islet cell (sub)populations, and define their molecular repertoire. However, precise understanding of cell type-specific alterations in type 2 diabetic vs. non-diabetic individuals is lacking, due in part to the limited number of individuals or single cell transcriptomes per individual profiled for comparison. Here, we create a comprehensive single cell transcriptome atlas of 245,878 human islet cells from 48 individuals spanning non-diabetic (ND), pre-diabetic (PD), and type 2 diabetic (T2D) states and matched for sex, age, and ancestry and define marker gene sets that are robustly expressed across disease states for each of the 14 cell types identified. We observe significant decreases in the number of beta cells sampled from T2D vs. ND or PD donors. Two of eight putative beta cell subpopulations, with â€˜high functioningâ€™ and â€˜senescentâ€™ cell gene signatures, increase and decrease in T2D donor islets, respectively. Importantly, we identify 511 differentially expressed genes in beta cells from T2D vs. ND donors. This includes monogenic and type 2 diabetes effector genes, such as HNF1A, DGKB, ST6GAL1, and FXYD2, for which genetic and environmental effects on their expression is concordant.Â  Human beta cell and islet knockdown of selected newly-identified down-regulated genes impairs beta cell viability or function. Together, this study provides new and robust, cell type-resolved insights on the cellular and molecular changes in healthy vs. diabetic human islets and represents a valuable resource to the islet biology and type 2 diabetes communities."
!Series_overall_design	"Pancreatic islets from 17 type 2 diabetic (T2D), 17 non-diabetic (ND) and 14 prediabetic (PD) cadaveric organ donors were dissociated to single cell suspension and captured/profiled using 10x Genomics single-cell RNA-seq platform"
!Series_overall_design	"ND: Islet29, Islet34, Islet37, Islet38, Islet42, Islet45, Islet47, Islet54, Islet57, Islet59, Islet61, Islet68, Islet73, Islet80, Islet104, Islet107, Islet123"
!Series_overall_design	"PD: Islet40, Islet50, Islet53, Islet55, Islet56, Islet58, Islet62, Islet63, Islet70, Islet85, Islet89, Islet101, Islet118, Islet127"
!Series_overall_design	"T2D:  Islet28, Islet30, Islet31, Islet32, Islet33, Islet39, Islet41, Islet44, Islet48, Islet52, Islet60, Islet71, Islet84, Islet91, Islet126, Islet119, Islet128"
!Series_type	"Expression profiling by high throughput sequencing"
!Series_contributor	"Efthymios,,Motakis"
!Series_contributor	"Siddhi,,Nargund"
!Series_contributor	"Romy,,Kursawe"
!Series_contributor	"Nathan,,Lawlor"
!Series_contributor	"Sai,N,Krishnan"
!Series_contributor	"Vijay,,Selvam"
!Series_contributor	"Michael,L,Stitzel"
!Series_sample_id	"GSM6846488 GSM6846489 GSM6846490 GSM6846491 GSM6846492 GSM6846493 GSM6846494 GSM6846495 GSM6846496 GSM6846497 GSM6846498 GSM6846499 GSM6846500 GSM6846501 GSM6846502 GSM6846503 GSM6846504 GSM6846505 GSM6846506 GSM6846507 GSM6846508 GSM6846509 GSM6846510 GSM6846511 GSM6846512 GSM6846513 GSM6846514 GSM6846515 GSM6846516 GSM6846517 GSM6846518 GSM6846519 GSM6846520 GSM6846521 GSM6846522 GSM6846523 GSM6846524 GSM6846525 GSM6846526 GSM6846527 GSM6846528 GSM6846529 GSM6846530 GSM6846531 GSM6846532 GSM6846533 GSM6846534 GSM6846535 GSM6846536 GSM6846537 GSM6846538 GSM6846539 GSM6846540 GSM6846541 "

In [5]:
for line in lines:
    if line.startswith("!Sample_"):
        print(line.strip())

!Sample_title	"Islet28"	"Islet29"	"Islet30"	"Islet31"	"Islet32"	"Islet33"	"Islet34"	"Islet37"	"Islet38"	"Islet39"	"Islet40"	"Islet41"	"Islet42"	"Islet44"	"Islet45"	"Islet47"	"Islet48"	"Islet47/48_MS19006"	"Islet47/48_MS19007"	"Islet50"	"Islet52"	"Islet53"	"Islet54"	"Islet55"	"Islet56"	"Islet57"	"Islet58"	"Islet57/58_MS19016"	"Islet57/58_MS19017"	"Islet59"	"Islet60"	"Islet59/60_MS19020"	"Islet59/60_MS19021"	"Islet61"	"Islet62"	"Islet63"	"Islet68"	"Islet70/71_MS19034"	"Islet70/71_MS19035"	"Islet73"	"Islet80"	"Islet84/85_MS19042"	"Islet84/85_MS19043"	"Islet89"	"Islet91"	"Islet101"	"Islet104"	"Islet107"	"Islet118/119_MS20086"	"Islet118/119_MS20087"	"Islet123"	"Islet126"	"Islet127"	"Islet128"
!Sample_geo_accession	"GSM6846488"	"GSM6846489"	"GSM6846490"	"GSM6846491"	"GSM6846492"	"GSM6846493"	"GSM6846494"	"GSM6846495"	"GSM6846496"	"GSM6846497"	"GSM6846498"	"GSM6846499"	"GSM6846500"	"GSM6846501"	"GSM6846502"	"GSM6846503"	"GSM6846504"	"GSM6846505"	"GSM6846506"	"GSM6846507"	"GSM6846508"	"GSM6846509"	"GSM6846510"	"GSM6846511"	"GSM6846512"	"GSM6846513"	"GSM6846514"	"GSM6846515"	"GSM6846516"	"GSM6846517"	"GSM6846518"	"GSM6846519"	"GSM6846520"	"GSM6846521"	"GSM6846522"	"GSM6846523"	"GSM6846524"	"GSM6846525"	"GSM6846526"	"GSM6846527"	"GSM6846528"	"GSM6846529"	"GSM6846530"	"GSM6846531"	"GSM6846532"	"GSM6846533"	"GSM6846534"	"GSM6846535"	"GSM6846536"	"GSM6846537"	"GSM6846538"	"GSM6846539"	"GSM6846540"	"GSM6846541"
!Sample_status	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"
!Sample_submission_date	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"
!Sample_last_update_date	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"
!Sample_type	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"
!Sample_channel_count	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"
!Sample_source_name_ch1	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"
!Sample_organism_ch1	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"
!Sample_characteristics_ch1	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"
!Sample_characteristics_ch1	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"
!Sample_characteristics_ch1	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"
!Sample_characteristics_ch1	"disease state: Type2Diabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: Type2Diabetic"	"disease state: Type2Diabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: PreDiabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic/Type2Diabetic"	"disease state: NonDiabetic/Type2Diabetic"	"disease state: PreDiabetic"	"disease state: Type2Diabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic/PreDiabetic"	"disease state: NonDiabetic/PreDiabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic/Type2Diabetic"	"disease state: NonDiabetic/Type2Diabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic/Type2Diabetic"	"disease state: PreDiabetic/Type2Diabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic/PreDiabetic"	"disease state: Type2Diabetic/PreDiabetic"	"disease state: PreDiabetic"	"disease state: Type2Diabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic/Type2Diabetic"	"disease state: PreDiabetic/Type2Diabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: PreDiabetic"	"disease state: Type2Diabetic"
!Sample_characteristics_ch1	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Female"	"Sex: Female"	"Sex: Female/Female"	"Sex: Female/Female"	"Sex: Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Female"	"Sex: Male"	"Sex: Female/Male"	"Sex: Female/Male"	"Sex: Male"	"Sex: Male"	"Sex: Male/Male"	"Sex: Male/Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Female/Male"	"Sex: Female/Male"	"Sex: Male"	"Sex: Male"	"Sex: Male/Male"	"Sex: Male/Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Male/Female"	"Sex: Male/Female"	"Sex: Female"	"Sex: Female"	"Sex: Male"	"Sex: Male"
!Sample_characteristics_ch1	"bmi: 35.6"	"bmi: 35.6"	"bmi: 42.8"	"bmi: 27.7"	"bmi: 27.7"	"bmi: 38.1"	"bmi: 25.3"	"bmi: 28.5"	"bmi: 27.3"	"bmi: 35.4"	"bmi: 30"	"bmi: 27.4"	"bmi: 27.2"	"bmi: 33.7"	"bmi: 24.6"	"bmi: 22.7"	"bmi: 33"	"bmi: 22.7/33"	"bmi: 22.7/33"	"bmi: 33.3"	"bmi: 31.7"	"bmi: 32"	"bmi: 24.2"	"bmi: 32.8"	"bmi: 39.8"	"bmi: 33.4"	"bmi: 26.7"	"bmi: 33.4/26.7"	"bmi: 33.4/26.7"	"bmi: 38.8"	"bmi: 32.5"	"bmi: 38.8/32.5"	"bmi: 38.8/32.5"	"bmi: 40"	"bmi: 32.6"	"bmi: 28.4"	"bmi: 29"	"bmi: 32.9/31.7"	"bmi: 32.9/31.7"	"bmi: 28.4"	"bmi: 25"	"bmi: 24.7/26.6"	"bmi: 24.7/26.6"	"bmi: 27.1"	"bmi: 25.8"	"bmi: 25.7"	"bmi: 20.2"	"bmi: 24.2"	"bmi: 31.6/28.5"	"bmi: 31.6/28.5"	"bmi: 28.3"	"bmi: 43.9"	"bmi: 29.9"	"bmi: 41.3"
!Sample_characteristics_ch1	"race: Hispanic"	"race: White"	"race: Hispanic"	"race: Hispanic"	"race: White"	"race: White"	"race: Hispanic"	"race: White"	"race: Hispanic"	"race: White"	"race: Hispanic"	"race: AfricanAmerican"	"race: White"	"race: AfricanAmerican"	"race: White"	"race: White"	"race: Hispanic"	"race: White/Hispanic"	"race: White/Hispanic"	"race: White"	"race: White"	"race: Hispanic"	"race: Hispanic"	"race: Hispanic"	"race: White"	"race: White"	"race: Hispanic"	"race: White/Hispanic"	"race: White/Hispanic"	"race: White"	"race: White"	"race: White/White"	"race: White/White"	"race: White"	"race: AfricanAmerican"	"race: AfricanAmerican"	"race: White"	"race: White/White"	"race: White/White"	"race: White"	"race: AfricanAmerican"	"race: Hispanic/Hispanic"	"race: Hispanic/Hispanic"	"race: Hispanic"	"race: White"	"race: White"	"race: AfricanAmerican"	"race: Hispanic"	"race: White/AfricanAmerican"	"race: White/AfricanAmerican"	"race: Hispanic"	"race: AfricanAmerican"	"race: White"	"race: Hispanic"
!Sample_characteristics_ch1	"hba1c: 7.1"	"hba1c: 5.1"	"hba1c: 6.6"	"hba1c: 6.5"	"hba1c: 6.3"	"hba1c: 8.2"	"hba1c: 5.3"	"hba1c: 5.2"	"hba1c: 5.4"	"hba1c: 9.9"	"hba1c: 6"	"hba1c: 7.9"	"hba1c: 4.7"	"hba1c: 8"	"hba1c: 5.1"	"hba1c: 4.8"	"hba1c: 13.1"	"hba1c: 4.8/13.1"	"hba1c: 4.8/13.1"	"hba1c: 5.7"	"hba1c: 7.3"	"hba1c: 5.8"	"hba1c: 5.5"	"hba1c: 6"	"hba1c: 6.4"	"hba1c: 5.4"	"hba1c: 5.7"	"hba1c: 5.4/5.7"	"hba1c: 5.4/5.7"	"hba1c: 5.4"	"hba1c: 6.7"	"hba1c: 5.4/6.7"	"hba1c: 5.4/6.7"	"hba1c: 5.5"	"hba1c: 5.8"	"hba1c: 5.9"	"hba1c: 5.1"	"hba1c: 5.7/5.9"	"hba1c: 5.7/5.9"	"hba1c: 5.6"	"hba1c: 5.5"	"hba1c: 6.1/6.1"	"hba1c: 6.1/6.1"	"hba1c: 5.8"	"hba1c: 6.7"	"hba1c: 5.9"	"hba1c: 5.2"	"hba1c: 5.2"	"hba1c: 5.9/7.6"	"hba1c: 5.9/7.6"	"hba1c: 4.6"	"hba1c: 7"	"hba1c: 5.8"	"hba1c: 7.5"
!Sample_characteristics_ch1	"age: 51"	"age: 54"	"age: 52"	"age: 59"	"age: 35"	"age: 37"	"age: 40"	"age: 32"	"age: 21"	"age: 50"	"age: 53"	"age: 61"	"age: 66"	"age: 54"	"age: 50"	"age: 53"	"age: 37"	"age: 53/37"	"age: 53/37"	"age: 53"	"age: 34"	"age: 62"	"age: 37"	"age: 50"	"age: 52"	"age: 35"	"age: 51"	"age: 35/51"	"age: 35/51"	"age: 48"	"age: 58"	"age: 48/58"	"age: 48/58"	"age: 53"	"age: 45"	"age: 49"	"age: 52"	"age: 57/63"	"age: 57/63"	"age: 55"	"age: 42"	"age: 52/58"	"age: 52/58"	"age: 30"	"age: 53"	"age: 48"	"age: 48"	"age: 26"	"age: 25/62"	"age: 25/62"	"age: 60"	"age: 38"	"age: 60"	"age: 60"
!Sample_characteristics_ch1	"center: Scharp-Lacy"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: UPenn"	"center: Scharp-Lacy"	"center: NA"	"center: Scharp-Lacy"	"center: Southern California IsletCell Resource Center"	"center: Southern California IsletCell Resource Center"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: UPenn"	"center: Miami"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Wisconsin"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Southern California IsletCell Resource Center"	"center: Scharp-Lacy"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Southern California IsletCell Resource Center"	"center: Scharp-Lacy/Southern California IsletCell Resource Center"	"center: Scharp-Lacy/Southern California IsletCell Resource Center"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Wisconsin/Scharp-Lacy"	"center: Wisconsin/Scharp-Lacy"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Wisconsin"	"center: Southern California IsletCell Resource Center/Scharp-Lacy"	"center: Southern California IsletCell Resource Center/Scharp-Lacy"	"center: Scharp-Lacy"	"center: Miami"	"center: Scharp-Lacy/Miami"	"center: Scharp-Lacy/Miami"	"center: Miami"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy/Southern California IsletCell Resource Center"	"center: Scharp-Lacy/Southern California IsletCell Resource Center"	"center: Scharp-Lacy"	"center: UPenn"	"center: UPenn"	"center: southern California IsletCell Resource Center"
!Sample_characteristics_ch1	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: Head trauma - gunshot wound/suicide"	"Cause of death: Head trauma"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: NR"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: Cerebrovascular/stroke / Head trauma"	"Cause of death: Cerebrovascular/stroke / Head trauma"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Anoxia"	"Cause of death: Cerebrovascular/stroke / Anoxia"	"Cause of death: Cerebrovascular/stroke / Anoxia"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Head trauma"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: NA"	"Cause of death: NA"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: Head trauma/NA"	"Cause of death: Head trauma/NA"	"Cause of death: Head trauma"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Cerebrovascular/stroke"

In [6]:
print(line.strip())

!series_matrix_table_end

In [7]:
for line in lines:
    if line.startswith("!Sample_"):
        print(line.strip())

!Sample_title	"Islet28"	"Islet29"	"Islet30"	"Islet31"	"Islet32"	"Islet33"	"Islet34"	"Islet37"	"Islet38"	"Islet39"	"Islet40"	"Islet41"	"Islet42"	"Islet44"	"Islet45"	"Islet47"	"Islet48"	"Islet47/48_MS19006"	"Islet47/48_MS19007"	"Islet50"	"Islet52"	"Islet53"	"Islet54"	"Islet55"	"Islet56"	"Islet57"	"Islet58"	"Islet57/58_MS19016"	"Islet57/58_MS19017"	"Islet59"	"Islet60"	"Islet59/60_MS19020"	"Islet59/60_MS19021"	"Islet61"	"Islet62"	"Islet63"	"Islet68"	"Islet70/71_MS19034"	"Islet70/71_MS19035"	"Islet73"	"Islet80"	"Islet84/85_MS19042"	"Islet84/85_MS19043"	"Islet89"	"Islet91"	"Islet101"	"Islet104"	"Islet107"	"Islet118/119_MS20086"	"Islet118/119_MS20087"	"Islet123"	"Islet126"	"Islet127"	"Islet128"
!Sample_geo_accession	"GSM6846488"	"GSM6846489"	"GSM6846490"	"GSM6846491"	"GSM6846492"	"GSM6846493"	"GSM6846494"	"GSM6846495"	"GSM6846496"	"GSM6846497"	"GSM6846498"	"GSM6846499"	"GSM6846500"	"GSM6846501"	"GSM6846502"	"GSM6846503"	"GSM6846504"	"GSM6846505"	"GSM6846506"	"GSM6846507"	"GSM6846508"	"GSM6846509"	"GSM6846510"	"GSM6846511"	"GSM6846512"	"GSM6846513"	"GSM6846514"	"GSM6846515"	"GSM6846516"	"GSM6846517"	"GSM6846518"	"GSM6846519"	"GSM6846520"	"GSM6846521"	"GSM6846522"	"GSM6846523"	"GSM6846524"	"GSM6846525"	"GSM6846526"	"GSM6846527"	"GSM6846528"	"GSM6846529"	"GSM6846530"	"GSM6846531"	"GSM6846532"	"GSM6846533"	"GSM6846534"	"GSM6846535"	"GSM6846536"	"GSM6846537"	"GSM6846538"	"GSM6846539"	"GSM6846540"	"GSM6846541"
!Sample_status	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"	"Public on Mar 30 2023"
!Sample_submission_date	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"	"Dec 16 2022"
!Sample_last_update_date	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"	"Jan 12 2026"
!Sample_type	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"
!Sample_channel_count	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"
!Sample_source_name_ch1	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"	"Pancreatic islets"
!Sample_organism_ch1	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"
!Sample_characteristics_ch1	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"	"tissue: Pancreatic islets"
!Sample_characteristics_ch1	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"	"treatment: None"
!Sample_characteristics_ch1	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V2"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"	"chemistry: V3"
!Sample_characteristics_ch1	"disease state: Type2Diabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: Type2Diabetic"	"disease state: Type2Diabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: PreDiabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic/Type2Diabetic"	"disease state: NonDiabetic/Type2Diabetic"	"disease state: PreDiabetic"	"disease state: Type2Diabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic/PreDiabetic"	"disease state: NonDiabetic/PreDiabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: NonDiabetic/Type2Diabetic"	"disease state: NonDiabetic/Type2Diabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic/Type2Diabetic"	"disease state: PreDiabetic/Type2Diabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic/PreDiabetic"	"disease state: Type2Diabetic/PreDiabetic"	"disease state: PreDiabetic"	"disease state: Type2Diabetic"	"disease state: PreDiabetic"	"disease state: NonDiabetic"	"disease state: NonDiabetic"	"disease state: PreDiabetic/Type2Diabetic"	"disease state: PreDiabetic/Type2Diabetic"	"disease state: NonDiabetic"	"disease state: Type2Diabetic"	"disease state: PreDiabetic"	"disease state: Type2Diabetic"
!Sample_characteristics_ch1	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Female"	"Sex: Female"	"Sex: Female/Female"	"Sex: Female/Female"	"Sex: Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Female"	"Sex: Female"	"Sex: Male"	"Sex: Female/Male"	"Sex: Female/Male"	"Sex: Male"	"Sex: Male"	"Sex: Male/Male"	"Sex: Male/Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Female/Male"	"Sex: Female/Male"	"Sex: Male"	"Sex: Male"	"Sex: Male/Male"	"Sex: Male/Male"	"Sex: Female"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Male"	"Sex: Male/Female"	"Sex: Male/Female"	"Sex: Female"	"Sex: Female"	"Sex: Male"	"Sex: Male"
!Sample_characteristics_ch1	"bmi: 35.6"	"bmi: 35.6"	"bmi: 42.8"	"bmi: 27.7"	"bmi: 27.7"	"bmi: 38.1"	"bmi: 25.3"	"bmi: 28.5"	"bmi: 27.3"	"bmi: 35.4"	"bmi: 30"	"bmi: 27.4"	"bmi: 27.2"	"bmi: 33.7"	"bmi: 24.6"	"bmi: 22.7"	"bmi: 33"	"bmi: 22.7/33"	"bmi: 22.7/33"	"bmi: 33.3"	"bmi: 31.7"	"bmi: 32"	"bmi: 24.2"	"bmi: 32.8"	"bmi: 39.8"	"bmi: 33.4"	"bmi: 26.7"	"bmi: 33.4/26.7"	"bmi: 33.4/26.7"	"bmi: 38.8"	"bmi: 32.5"	"bmi: 38.8/32.5"	"bmi: 38.8/32.5"	"bmi: 40"	"bmi: 32.6"	"bmi: 28.4"	"bmi: 29"	"bmi: 32.9/31.7"	"bmi: 32.9/31.7"	"bmi: 28.4"	"bmi: 25"	"bmi: 24.7/26.6"	"bmi: 24.7/26.6"	"bmi: 27.1"	"bmi: 25.8"	"bmi: 25.7"	"bmi: 20.2"	"bmi: 24.2"	"bmi: 31.6/28.5"	"bmi: 31.6/28.5"	"bmi: 28.3"	"bmi: 43.9"	"bmi: 29.9"	"bmi: 41.3"
!Sample_characteristics_ch1	"race: Hispanic"	"race: White"	"race: Hispanic"	"race: Hispanic"	"race: White"	"race: White"	"race: Hispanic"	"race: White"	"race: Hispanic"	"race: White"	"race: Hispanic"	"race: AfricanAmerican"	"race: White"	"race: AfricanAmerican"	"race: White"	"race: White"	"race: Hispanic"	"race: White/Hispanic"	"race: White/Hispanic"	"race: White"	"race: White"	"race: Hispanic"	"race: Hispanic"	"race: Hispanic"	"race: White"	"race: White"	"race: Hispanic"	"race: White/Hispanic"	"race: White/Hispanic"	"race: White"	"race: White"	"race: White/White"	"race: White/White"	"race: White"	"race: AfricanAmerican"	"race: AfricanAmerican"	"race: White"	"race: White/White"	"race: White/White"	"race: White"	"race: AfricanAmerican"	"race: Hispanic/Hispanic"	"race: Hispanic/Hispanic"	"race: Hispanic"	"race: White"	"race: White"	"race: AfricanAmerican"	"race: Hispanic"	"race: White/AfricanAmerican"	"race: White/AfricanAmerican"	"race: Hispanic"	"race: AfricanAmerican"	"race: White"	"race: Hispanic"
!Sample_characteristics_ch1	"hba1c: 7.1"	"hba1c: 5.1"	"hba1c: 6.6"	"hba1c: 6.5"	"hba1c: 6.3"	"hba1c: 8.2"	"hba1c: 5.3"	"hba1c: 5.2"	"hba1c: 5.4"	"hba1c: 9.9"	"hba1c: 6"	"hba1c: 7.9"	"hba1c: 4.7"	"hba1c: 8"	"hba1c: 5.1"	"hba1c: 4.8"	"hba1c: 13.1"	"hba1c: 4.8/13.1"	"hba1c: 4.8/13.1"	"hba1c: 5.7"	"hba1c: 7.3"	"hba1c: 5.8"	"hba1c: 5.5"	"hba1c: 6"	"hba1c: 6.4"	"hba1c: 5.4"	"hba1c: 5.7"	"hba1c: 5.4/5.7"	"hba1c: 5.4/5.7"	"hba1c: 5.4"	"hba1c: 6.7"	"hba1c: 5.4/6.7"	"hba1c: 5.4/6.7"	"hba1c: 5.5"	"hba1c: 5.8"	"hba1c: 5.9"	"hba1c: 5.1"	"hba1c: 5.7/5.9"	"hba1c: 5.7/5.9"	"hba1c: 5.6"	"hba1c: 5.5"	"hba1c: 6.1/6.1"	"hba1c: 6.1/6.1"	"hba1c: 5.8"	"hba1c: 6.7"	"hba1c: 5.9"	"hba1c: 5.2"	"hba1c: 5.2"	"hba1c: 5.9/7.6"	"hba1c: 5.9/7.6"	"hba1c: 4.6"	"hba1c: 7"	"hba1c: 5.8"	"hba1c: 7.5"
!Sample_characteristics_ch1	"age: 51"	"age: 54"	"age: 52"	"age: 59"	"age: 35"	"age: 37"	"age: 40"	"age: 32"	"age: 21"	"age: 50"	"age: 53"	"age: 61"	"age: 66"	"age: 54"	"age: 50"	"age: 53"	"age: 37"	"age: 53/37"	"age: 53/37"	"age: 53"	"age: 34"	"age: 62"	"age: 37"	"age: 50"	"age: 52"	"age: 35"	"age: 51"	"age: 35/51"	"age: 35/51"	"age: 48"	"age: 58"	"age: 48/58"	"age: 48/58"	"age: 53"	"age: 45"	"age: 49"	"age: 52"	"age: 57/63"	"age: 57/63"	"age: 55"	"age: 42"	"age: 52/58"	"age: 52/58"	"age: 30"	"age: 53"	"age: 48"	"age: 48"	"age: 26"	"age: 25/62"	"age: 25/62"	"age: 60"	"age: 38"	"age: 60"	"age: 60"
!Sample_characteristics_ch1	"center: Scharp-Lacy"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: UPenn"	"center: Scharp-Lacy"	"center: NA"	"center: Scharp-Lacy"	"center: Southern California IsletCell Resource Center"	"center: Southern California IsletCell Resource Center"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: UPenn"	"center: Miami"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Wisconsin"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Southern California IsletCell Resource Center"	"center: Scharp-Lacy"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Southern California IsletCell Resource Center"	"center: Scharp-Lacy/Southern California IsletCell Resource Center"	"center: Scharp-Lacy/Southern California IsletCell Resource Center"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Wisconsin/Scharp-Lacy"	"center: Wisconsin/Scharp-Lacy"	"center: Wisconsin"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Wisconsin"	"center: Southern California IsletCell Resource Center/Scharp-Lacy"	"center: Southern California IsletCell Resource Center/Scharp-Lacy"	"center: Scharp-Lacy"	"center: Miami"	"center: Scharp-Lacy/Miami"	"center: Scharp-Lacy/Miami"	"center: Miami"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy"	"center: Scharp-Lacy/Southern California IsletCell Resource Center"	"center: Scharp-Lacy/Southern California IsletCell Resource Center"	"center: Scharp-Lacy"	"center: UPenn"	"center: UPenn"	"center: southern California IsletCell Resource Center"
!Sample_characteristics_ch1	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: Head trauma - gunshot wound/suicide"	"Cause of death: Head trauma"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: NR"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: Cerebrovascular/stroke / Head trauma"	"Cause of death: Cerebrovascular/stroke / Head trauma"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Anoxia"	"Cause of death: Cerebrovascular/stroke / Anoxia"	"Cause of death: Cerebrovascular/stroke / Anoxia"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Head trauma"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: NA"	"Cause of death: NA"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Cerebrovascular/stroke"	"Cause of death: Head trauma"	"Cause of death: Head trauma/NA"	"Cause of death: Head trauma/NA"	"Cause of death: Head trauma"	"Cause of death: Anoxia"	"Cause of death: Anoxia"	"Cause of death: Cerebrovascular/stroke"

In [8]:
records = []

# Find the sample IDs and sample titles
geo_line = next(line for line in lines if line.startswith("!Sample_geo_accession"))
title_line = next(line for line in lines if line.startswith("!Sample_title"))

geo_ids = [x.strip('"') for x in geo_line.strip().split("\t")[1:]]
titles = [x.strip('"') for x in title_line.strip().split("\t")[1:]]

# Create one record for each sample
for gsm, title in zip(geo_ids, titles):
    records.append({
        "GSM": gsm,
        "sample_title": title
    })

# Add all the sample characteristics
for line in lines:
    if line.startswith("!Sample_characteristics_ch1"):
        values = [x.strip('"') for x in line.strip().split("\t")[1:]]

        for i, value in enumerate(values):
            if ": " in value:
                key, val = value.split(": ", 1)

                # Clean column names
                key = key.strip().lower().replace(" ", "_")

                records[i][key] = val.strip()

metadata_df = pd.DataFrame(records)

metadata_df.head()

,GSM,sample_title,tissue,treatment,chemistry,disease_state,sex,bmi,race,hba1c,age,center,cause_of_death,library_id
0,GSM6846488,Islet28,Pancreatic islets,None,V2,Type2Diabetic,Male,35.6,Hispanic,7.1,51,Scharp-Lacy,Cerebrovascular/stroke,MS17001
1,GSM6846489,Islet29,Pancreatic islets,None,V2,NonDiabetic,Male,35.6,White,5.1,54,Wisconsin,Cerebrovascular/stroke,MS17002
2,GSM6846490,Islet30,Pancreatic islets,None,V2,Type2Diabetic,Female,42.8,Hispanic,6.6,52,Scharp-Lacy,Cerebrovascular/stroke,MS17003
3,GSM6846491,Islet31,Pancreatic islets,None,V2,Type2Diabetic,Male,27.7,Hispanic,6.5,59,Scharp-Lacy,Cerebrovascular/stroke,MS17004
4,GSM6846492,Islet32,Pancreatic islets,None,V2,Type2Diabetic,Male,27.7,White,6.3,35,Scharp-Lacy,Cerebrovascular/stroke,MS17005

In [9]:
print("Number of samples:", metadata_df.shape[0])
print("Number of columns:", metadata_df.shape[1])

print("\nDisease-state counts:")
print(metadata_df["disease_state"].value_counts(dropna=False))

Number of samples: 54
Number of columns: 14

Disease-state counts:
disease_state
NonDiabetic                  17
Type2Diabetic                14
PreDiabetic                  11
NonDiabetic/Type2Diabetic     4
PreDiabetic/Type2Diabetic     4
NonDiabetic/PreDiabetic       2
Type2Diabetic/PreDiabetic     2
Name: count, dtype: int64

In [10]:
metadata_df[["GSM", "sample_title", "disease_state", "sex", "bmi"]].head(10)

          GSM sample_title  disease_state     sex   bmi
0  GSM6846488      Islet28  Type2Diabetic    Male  35.6
1  GSM6846489      Islet29    NonDiabetic    Male  35.6
2  GSM6846490      Islet30  Type2Diabetic  Female  42.8
3  GSM6846491      Islet31  Type2Diabetic    Male  27.7
4  GSM6846492      Islet32  Type2Diabetic    Male  27.7
5  GSM6846493      Islet33  Type2Diabetic  Female  38.1
6  GSM6846494      Islet34    NonDiabetic    Male  25.3
7  GSM6846495      Islet37    NonDiabetic    Male  28.5
8  GSM6846496      Islet38    NonDiabetic    Male  27.3
9  GSM6846497      Islet39  Type2Diabetic  Female  35.4

In [11]:
print("Total GEO samples:", len(metadata_df))

print("\nUnique sample titles:")
print(metadata_df["sample_title"].nunique())

print("\nDuplicate sample titles:")
print(metadata_df["sample_title"].duplicated().sum())

Total GEO samples: 54

Unique sample titles:
54

Duplicate sample titles:
0

In [12]:
duplicates = metadata_df[
    metadata_df["sample_title"].duplicated(keep=False)
].sort_values("sample_title")

duplicates[["GSM", "sample_title", "disease_state", "sex", "bmi"]]

Empty DataFrame
Columns: [GSM, sample_title, disease_state, sex, bmi]
Index: []

In [13]:
print("All metadata columns:")
for col in metadata_df.columns:
    print(col)

All metadata columns:
GSM
sample_title
tissue
treatment
chemistry
disease_state
sex
bmi
race
hba1c
age
center
cause_of_death
library_id

In [14]:
candidate_cols = [
    col for col in metadata_df.columns
    if any(word in col.lower() for word in
           ["donor", "subject", "individual", "library", "sample"])
]

print("Possible donor/sample ID columns:")
print(candidate_cols)

Possible donor/sample ID columns:
['sample_title', 'library_id']

In [15]:
metadata_df[[
    "GSM",
    "sample_title",
    "library_id",
    "disease_state",
    "sex",
    "bmi"
]].head(20)

,GSM,sample_title,library_id,disease_state,sex,bmi
0,GSM6846488,Islet28,MS17001,Type2Diabetic,Male,35.6
1,GSM6846489,Islet29,MS17002,NonDiabetic,Male,35.6
2,GSM6846490,Islet30,MS17003,Type2Diabetic,Female,42.8
3,GSM6846491,Islet31,MS17004,Type2Diabetic,Male,27.7
4,GSM6846492,Islet32,MS17005,Type2Diabetic,Male,27.7
5,GSM6846493,Islet33,MS17006,Type2Diabetic,Female,38.1
6,GSM6846494,Islet34,MS18001,NonDiabetic,Male,25.3
7,GSM6846495,Islet37,MS18002,NonDiabetic,Male,28.5
8,GSM6846496,Islet38,MS18003,NonDiabetic,Male,27.3
9,GSM6846497,Islet39,MS18004,Type2Diabetic,Female,35.4
10,GSM6846498,Islet40,MS18005,PreDiabetic,Female,30
11,GSM6846499,Islet41,MS18006,Type2Diabetic,Male,27.4
12,GSM6846500,Islet42,MS19001,NonDiabetic,Male,27.2
13,GSM6846501,Islet44,MS19002,Type2Diabetic,Male,33.7
14,GSM6846502,Islet45,MS19003,NonDiabetic,Female,24.6
15,GSM6846503,Islet47,MS19004,NonDiabetic,Female,22.7
16,GSM6846504,Islet48,MS19005,Type2Diabetic,Female,33
17,GSM6846505,Islet47/48_MS19006,MS19006,NonDiabetic/Type2Diabetic,Female/Female,22.7/33
18,GSM6846506,Islet47/48_MS19007,MS19007,NonDiabetic/Type2Diabetic,Female/Female,22.7/33
19,GSM6846507,Islet50,MS19008,PreDiabetic,Male,33.3

In [16]:
print("Total GEO samples:", len(metadata_df))
print("Unique sample titles:", metadata_df["sample_title"].nunique())
print("Unique library IDs:", metadata_df["library_id"].nunique())

print("\nMost common library IDs:")
print(metadata_df["library_id"].value_counts().head(15))

Total GEO samples: 54
Unique sample titles: 54
Unique library IDs: 54

Most common library IDs:
library_id
MS17001    1
MS17002    1
MS17003    1
MS17004    1
MS17005    1
MS17006    1
MS18001    1
MS18002    1
MS18003    1
MS18004    1
MS18005    1
MS18006    1
MS19001    1
MS19002    1
MS19003    1
Name: count, dtype: int64

In [17]:
import pyreadr
from pathlib import Path

beta_rds = Path("../data/processed/Rmarkdown/BetaPseudobulk.rds")

print("File exists:", beta_rds.exists())
print("File size (MB):", round(beta_rds.stat().st_size / (1024**2), 2))

File exists: True
File size (MB): 2.03

In [18]:
result = pyreadr.read_r(beta_rds)

print("Objects found inside the RDS file:")
print(result.keys())

Objects found inside the RDS file:
odict_keys([])